"""Adiciona campos de codigo unico para Material e Venda 2

Revision ID: 2a6a445900b0
Revises: d3e3b0e45ee8
Create Date: 2025-09-25 14:25:16.471184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6a445900b0'
down_revision: Union[str, Sequence[str], None] = 'd3e3b0e45ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entradas_material', sa.Column('codigo_lote', sa.String(), nullable=False))
    op.create_index(op.f('ix_entradas_material_codigo_lote'), 'entradas_material', ['codigo_lote'], unique=True)
    op.add_column('materiais', sa.Column('codigo_material', sa.String(), nullable=False))
    op.create_index(op.f('ix_materiais_codigo_material'), 'materiais', ['codigo_material'], unique=True)
    op.add_column('vendas', sa.Column('codigo_venda', sa.String(), nullable=False))
    op.create_index(op.f('ix_vendas_codigo_venda'), 'vendas', ['codigo_venda'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendas_codigo_venda'), table_name='vendas')
    op.drop_column('vendas', 'codigo_venda')
    op.drop_index(op.f('ix_materiais_codigo_material'), table_name='materiais')
    op.drop_column('materiais', 'codigo_material')
    op.drop_index(op.f('ix_entradas_material_codigo_lote'), table_name='entradas_material')
    op.drop_column('entradas_material', 'codigo_lote')
    # ### end Alembic commands ###
