"""Cria estrutura inicial de tabelas

Revision ID: 325fa84c8b3b
Revises: adc53b33bc7a
Create Date: 2025-09-24 17:12:59.319498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325fa84c8b3b'
down_revision: Union[str, Sequence[str], None] = 'adc53b33bc7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
