"""adc_coluna_observado

Revision ID: 3b62a63934e7
Revises: 16df2710a492
Create Date: 2026-04-21 20:30:14.098159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b62a63934e7'
down_revision: Union[str, Sequence[str], None] = '16df2710a492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producao_impacto', sa.Column('observado', sa.String(length=255), nullable=True))
    op.drop_column('producao_impacto', 'observacoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producao_impacto', sa.Column('observacoes', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('producao_impacto', 'observado')
    # ### end Alembic commands ###
