"""Padroniza nome da coluna codigo_venda para codigo

Revision ID: 5050de469781
Revises: 7f6f75b8fc35
Create Date: 2025-10-14 16:19:46.516651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5050de469781'
down_revision: Union[str, Sequence[str], None] = '7f6f75b8fc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('codigo', sa.String(), nullable=False))
    op.drop_index(op.f('ix_vendas_codigo_venda'), table_name='vendas')
    op.create_index(op.f('ix_vendas_codigo'), 'vendas', ['codigo'], unique=True)
    op.drop_column('vendas', 'codigo_venda')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('codigo_venda', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_vendas_codigo'), table_name='vendas')
    op.create_index(op.f('ix_vendas_codigo_venda'), 'vendas', ['codigo_venda'], unique=True)
    op.drop_column('vendas', 'codigo')
    # ### end Alembic commands ###
