"""Cria tabela CategoriaResiduo e linka em Material

Revision ID: 66203f355943
Revises: ccabf74e1aeb
Create Date: 2025-11-11 23:45:23.660096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66203f355943'
down_revision: Union[str, Sequence[str], None] = 'ccabf74e1aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_residuo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    categoria_table = sa.table('categoria_residuo',
    sa.column('id', sa.Integer),
    sa.column('nome', sa.String))
    op.bulk_insert(categoria_table,
    [
        {'nome': 'Plástico'},
        {'nome': 'Papel'},
        {'nome': 'Metal'},
        {'nome': 'Vidro'},
        {'nome': 'Orgânico'},
        {'nome': 'Rejeito'}
    ]
)
    op.create_index(op.f('ix_categoria_residuo_id'), 'categoria_residuo', ['id'], unique=False)
    op.create_index(op.f('ix_categoria_residuo_nome'), 'categoria_residuo', ['nome'], unique=True)
    op.add_column('materiais', sa.Column('id_categoria', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_materiais_categoria'), table_name='materiais')
    op.create_foreign_key(None, 'materiais', 'categoria_residuo', ['id_categoria'], ['id'])
    op.drop_column('materiais', 'categoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materiais', sa.Column('categoria', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'materiais', type_='foreignkey')
    op.create_index(op.f('ix_materiais_categoria'), 'materiais', ['categoria'], unique=False)
    op.drop_column('materiais', 'id_categoria')
    op.drop_index(op.f('ix_categoria_residuo_nome'), table_name='categoria_residuo')
    op.drop_index(op.f('ix_categoria_residuo_id'), table_name='categoria_residuo')
    op.drop_table('categoria_residuo')
    # ### end Alembic commands ###
