"""Adiciona campo ativo a materiais para soft delete

Revision ID: 732266b2beff
Revises: 09a0d0f2f23a
Create Date: 2025-10-21 01:36:40.468845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732266b2beff'
down_revision: Union[str, Sequence[str], None] = '09a0d0f2f23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('associacoes', sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('associacoes', 'ativo')
    # ### end Alembic commands ###
