"""Adiciona campo status a vendas

Revision ID: 7f886c62c23f
Revises: a7b973a8f740
Create Date: 2025-10-21 13:58:33.061571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f886c62c23f'
down_revision: Union[str, Sequence[str], None] = 'a7b973a8f740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('concluida', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas', 'concluida')
    # ### end Alembic commands ###
