"""Versao 2.0: Implementa arquitetura Doador e Comprador

Revision ID: a012f8de6d4c
Revises: 
Create Date: 2025-11-04 01:42:12.627361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a012f8de6d4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compradores_cnpj'), 'compradores', ['cnpj'], unique=True)
    op.create_index(op.f('ix_compradores_id'), 'compradores', ['id'], unique=False)
    op.create_index(op.f('ix_compradores_nome'), 'compradores', ['nome'], unique=True)
    op.create_table('materiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('unidade_medida', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiais_categoria'), 'materiais', ['categoria'], unique=False)
    op.create_index(op.f('ix_materiais_codigo'), 'materiais', ['codigo'], unique=True)
    op.create_index(op.f('ix_materiais_id'), 'materiais', ['id'], unique=False)
    op.create_index(op.f('ix_materiais_nome'), 'materiais', ['nome'], unique=True)
    tipo_doador_table = op.create_table('tipo_doador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.bulk_insert(tipo_doador_table,
        [
            {'nome': 'ASSOCIACAO'},
            {'nome': 'ORGAO_PUBLICO'},
            {'nome': 'EMPRESA_PRIVADA'},
            {'nome': 'PESSOA_FISICA'},
            {'nome': 'OUTRO'}
        ]
    )
    
    op.create_index(op.f('ix_tipo_doador_id'), 'tipo_doador', ['id'], unique=False)
    op.create_table('doadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('id_tipo_doador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_doador'], ['tipo_doador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doadores_id'), 'doadores', ['id'], unique=False)
    op.create_index(op.f('ix_doadores_nome'), 'doadores', ['nome'], unique=True)
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('data_venda', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('concluida', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id_comprador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_comprador'], ['compradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendas_codigo'), 'vendas', ['codigo'], unique=True)
    op.create_index(op.f('ix_vendas_id'), 'vendas', ['id'], unique=False)
    op.create_table('associacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doador_id', sa.Integer(), nullable=False),
    sa.Column('lider', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['doador_id'], ['doadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doador_id')
    )
    op.create_index(op.f('ix_associacoes_cnpj'), 'associacoes', ['cnpj'], unique=False)
    op.create_index(op.f('ix_associacoes_id'), 'associacoes', ['id'], unique=False)
    op.create_table('entradas_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_lote', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('data_entrada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), server_default='Confirmada', nullable=False),
    sa.Column('id_doador', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_doador'], ['doadores.id'], ),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entradas_material_codigo_lote'), 'entradas_material', ['codigo_lote'], unique=True)
    op.create_index(op.f('ix_entradas_material_id'), 'entradas_material', ['id'], unique=False)
    op.create_table('itens_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade_vendida', sa.Float(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('id_venda', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['id_venda'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_venda_id'), 'itens_venda', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_venda_id'), table_name='itens_venda')
    op.drop_table('itens_venda')
    op.drop_index(op.f('ix_entradas_material_id'), table_name='entradas_material')
    op.drop_index(op.f('ix_entradas_material_codigo_lote'), table_name='entradas_material')
    op.drop_table('entradas_material')
    op.drop_index(op.f('ix_associacoes_id'), table_name='associacoes')
    op.drop_index(op.f('ix_associacoes_cnpj'), table_name='associacoes')
    op.drop_table('associacoes')
    op.drop_index(op.f('ix_vendas_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_codigo'), table_name='vendas')
    op.drop_table('vendas')
    op.drop_index(op.f('ix_doadores_nome'), table_name='doadores')
    op.drop_index(op.f('ix_doadores_id'), table_name='doadores')
    op.drop_table('doadores')
    op.drop_index(op.f('ix_tipo_doador_id'), table_name='tipo_doador')
    op.drop_table('tipo_doador')
    op.drop_index(op.f('ix_materiais_nome'), table_name='materiais')
    op.drop_index(op.f('ix_materiais_id'), table_name='materiais')
    op.drop_index(op.f('ix_materiais_codigo'), table_name='materiais')
    op.drop_index(op.f('ix_materiais_categoria'), table_name='materiais')
    op.drop_table('materiais')
    op.drop_index(op.f('ix_compradores_nome'), table_name='compradores')
    op.drop_index(op.f('ix_compradores_id'), table_name='compradores')
    op.drop_index(op.f('ix_compradores_cnpj'), table_name='compradores')
    op.drop_table('compradores')
    # ### end Alembic commands ###
