"""Adiciona campo status a entradas_material

Revision ID: a7b973a8f740
Revises: 70628cbbb0e9
Create Date: 2025-10-21 13:51:48.082589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b973a8f740'
down_revision: Union[str, Sequence[str], None] = '70628cbbb0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entradas_material', sa.Column('status', sa.String(), server_default='Confirmada', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entradas_material', 'status')
    # ### end Alembic commands ###
