"""Cria a estrutura inicial de tabelas do projeto

Revision ID: adc53b33bc7a
Revises: 
Create Date: 2025-09-17 17:15:29.389266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc53b33bc7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('lider', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_associacoes_cnpj'), 'associacoes', ['cnpj'], unique=False)
    op.create_index(op.f('ix_associacoes_id'), 'associacoes', ['id'], unique=False)
    op.create_index(op.f('ix_associacoes_nome'), 'associacoes', ['nome'], unique=False)
    op.create_table('compradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('contato', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compradores_id'), 'compradores', ['id'], unique=False)
    op.create_index(op.f('ix_compradores_nome'), 'compradores', ['nome'], unique=True)
    op.create_table('materiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('unidade_medida', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiais_id'), 'materiais', ['id'], unique=False)
    op.create_index(op.f('ix_materiais_nome'), 'materiais', ['nome'], unique=True)
    op.create_table('entradas_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('data_entrada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('id_associacao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_associacao'], ['associacoes.id'], ),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entradas_material_id'), 'entradas_material', ['id'], unique=False)
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_venda', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_comprador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_comprador'], ['compradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendas_id'), 'vendas', ['id'], unique=False)
    op.create_table('itens_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade_vendida', sa.Float(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('id_venda', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['id_venda'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_venda_id'), 'itens_venda', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_venda_id'), table_name='itens_venda')
    op.drop_table('itens_venda')
    op.drop_index(op.f('ix_vendas_id'), table_name='vendas')
    op.drop_table('vendas')
    op.drop_index(op.f('ix_entradas_material_id'), table_name='entradas_material')
    op.drop_table('entradas_material')
    op.drop_index(op.f('ix_materiais_nome'), table_name='materiais')
    op.drop_index(op.f('ix_materiais_id'), table_name='materiais')
    op.drop_table('materiais')
    op.drop_index(op.f('ix_compradores_nome'), table_name='compradores')
    op.drop_index(op.f('ix_compradores_id'), table_name='compradores')
    op.drop_table('compradores')
    op.drop_index(op.f('ix_associacoes_nome'), table_name='associacoes')
    op.drop_index(op.f('ix_associacoes_id'), table_name='associacoes')
    op.drop_index(op.f('ix_associacoes_cnpj'), table_name='associacoes')
    op.drop_table('associacoes')
    # ### end Alembic commands ###
