"""create grupo and municipio tables

Revision ID: b1a6f58fce3c
Revises: 950576b57d5b
Create Date: 2026-03-14 15:59:24.329878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a6f58fce3c'
down_revision: Union[str, Sequence[str], None] = '950576b57d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('qtd_grupos', sa.Integer(), nullable=True),
    sa.Column('qtd_associacoes', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipios_id'), 'municipios', ['id'], unique=False)
    op.create_index(op.f('ix_municipios_nome'), 'municipios', ['nome'], unique=True)
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('integrantes', sa.Integer(), nullable=True),
    sa.Column('associacao_id', sa.Integer(), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['associacao_id'], ['associacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_associacao_id'), 'grupos', ['associacao_id'], unique=False)
    op.create_index(op.f('ix_grupos_id'), 'grupos', ['id'], unique=False)
    op.create_index(op.f('ix_grupos_nome'), 'grupos', ['nome'], unique=False)
    op.alter_column('usuarios', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('ix_grupos_nome'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_id'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_associacao_id'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_municipios_nome'), table_name='municipios')
    op.drop_index(op.f('ix_municipios_id'), table_name='municipios')
    op.drop_table('municipios')
    # ### end Alembic commands ###
