"""add da coluna cidade e uf em grupo

Revision ID: d177c25eab92
Revises: d36e43af205d
Create Date: 2026-04-23 01:16:56.888844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd177c25eab92'
down_revision: Union[str, Sequence[str], None] = 'd36e43af205d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('associacoes', 'qtd_integrantes',
               existing_type=sa.INTEGER(),
               nullable=0)
    op.add_column('grupos', sa.Column('cidade', sa.String(length=42), nullable=False))
    op.add_column('grupos', sa.Column('uf', sa.String(length=42), nullable=False))
    op.create_index(op.f('ix_grupos_cidade'), 'grupos', ['cidade'], unique=False)
    op.create_index(op.f('ix_grupos_uf'), 'grupos', ['uf'], unique=False)
    op.alter_column('municipios', 'qtd_integrantes',
               existing_type=sa.INTEGER(),
               nullable=0)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('municipios', 'qtd_integrantes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_grupos_uf'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_cidade'), table_name='grupos')
    op.drop_column('grupos', 'uf')
    op.drop_column('grupos', 'cidade')
    op.alter_column('associacoes', 'qtd_integrantes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
