"""add da coluna qtd_integrantes

Revision ID: d36e43af205d
Revises: 3b62a63934e7
Create Date: 2026-04-22 21:06:33.875608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd36e43af205d'
down_revision: Union[str, Sequence[str], None] = '3b62a63934e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_afiliados_cpf'), table_name='afiliados')
    op.drop_index(op.f('ix_afiliados_cpf_hash'), table_name='afiliados')
    op.drop_index(op.f('ix_afiliados_id'), table_name='afiliados')
    op.drop_table('afiliados')
    op.add_column('associacoes', sa.Column('qtd_integrantes', sa.Integer(), nullable=0))
    op.add_column('grupos', sa.Column('qtd_integrantes', sa.Integer(), nullable=False))
    op.add_column('municipios', sa.Column('qtd_integrantes', sa.Integer(), nullable=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('municipios', 'qtd_integrantes')
    op.drop_column('grupos', 'qtd_integrantes')
    op.drop_column('associacoes', 'qtd_integrantes')
    op.create_table('afiliados',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=14), autoincrement=False, nullable=True),
    sa.Column('cpf_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('funcao', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('data_filiacao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('associacao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['associacao_id'], ['associacoes.id'], name=op.f('afiliados_associacao_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('afiliados_pkey'))
    )
    op.create_index(op.f('ix_afiliados_id'), 'afiliados', ['id'], unique=False)
    op.create_index(op.f('ix_afiliados_cpf_hash'), 'afiliados', ['cpf_hash'], unique=False)
    op.create_index(op.f('ix_afiliados_cpf'), 'afiliados', ['cpf'], unique=True)
    # ### end Alembic commands ###
