"""Adiciona campos de codigo unico para Material e Venda

Revision ID: d3e3b0e45ee8
Revises: 325fa84c8b3b
Create Date: 2025-09-25 14:15:32.684529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e3b0e45ee8'
down_revision: Union[str, Sequence[str], None] = '325fa84c8b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
