"""create producao_mensal table

Revision ID: d66031aa8eb1
Revises: 
Create Date: 2026-03-14 14:34:56.784055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd66031aa8eb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_residuo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_residuo_id'), 'categoria_residuo', ['id'], unique=False)
    op.create_index(op.f('ix_categoria_residuo_nome'), 'categoria_residuo', ['nome'], unique=True)
    op.create_table('compradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compradores_cnpj'), 'compradores', ['cnpj'], unique=True)
    op.create_index(op.f('ix_compradores_id'), 'compradores', ['id'], unique=False)
    op.create_index(op.f('ix_compradores_nome'), 'compradores', ['nome'], unique=True)
    op.create_table('enderecos_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('logradouro', sa.Text(), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('consulted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enderecos_cache_cnpj'), 'enderecos_cache', ['cnpj'], unique=True)
    op.create_index(op.f('ix_enderecos_cache_id'), 'enderecos_cache', ['id'], unique=False)
    op.create_table('tipo_parceiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_tipo_parceiro_id'), 'tipo_parceiro', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('tabela_afetada', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('dados_antigos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dados_novos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_acao'), 'audit_logs', ['acao'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_usuario_id'), 'audit_logs', ['usuario_id'], unique=False)
    op.create_table('materiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('unidade_medida', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_residuo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiais_codigo'), 'materiais', ['codigo'], unique=True)
    op.create_index(op.f('ix_materiais_id'), 'materiais', ['id'], unique=False)
    op.create_index(op.f('ix_materiais_nome'), 'materiais', ['nome'], unique=True)
    op.create_table('parceiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('id_tipo_parceiro', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_parceiro'], ['tipo_parceiro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parceiros_id'), 'parceiros', ['id'], unique=False)
    op.create_index(op.f('ix_parceiros_nome'), 'parceiros', ['nome'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('data_venda', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('concluida', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id_comprador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_comprador'], ['compradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendas_codigo'), 'vendas', ['codigo'], unique=True)
    op.create_index(op.f('ix_vendas_id'), 'vendas', ['id'], unique=False)
    op.create_table('associacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('lider', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('logradouro', sa.Text(), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parceiro_id')
    )
    op.create_index(op.f('ix_associacoes_cnpj'), 'associacoes', ['cnpj'], unique=False)
    op.create_index(op.f('ix_associacoes_id'), 'associacoes', ['id'], unique=False)
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_compra', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('valor_pago_unitario', sa.Float(), nullable=False),
    sa.Column('valor_pago_total', sa.Float(), nullable=False),
    sa.Column('data_compra', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), server_default='Concluída', nullable=False),
    sa.Column('id_parceiro', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['id_parceiro'], ['parceiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_codigo_compra'), 'compras', ['codigo_compra'], unique=True)
    op.create_index(op.f('ix_compras_id'), 'compras', ['id'], unique=False)
    op.create_table('itens_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade_vendida', sa.Float(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('id_venda', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['id_venda'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_venda_id'), 'itens_venda', ['id'], unique=False)
    op.create_table('recebimentos_doacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_lote', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('data_entrada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), server_default='Confirmada', nullable=False),
    sa.Column('id_parceiro', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['id_parceiro'], ['parceiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recebimentos_doacao_codigo_lote'), 'recebimentos_doacao', ['codigo_lote'], unique=True)
    op.create_index(op.f('ix_recebimentos_doacao_id'), 'recebimentos_doacao', ['id'], unique=False)
    op.create_table('producao_mensal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('associacao_id', sa.Integer(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_venda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observado', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='check_mes_valido'),
    sa.ForeignKeyConstraint(['associacao_id'], ['associacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('associacao_id', 'mes', 'ano', name='uq_producao_mes_ano')
    )
    op.create_index(op.f('ix_producao_mensal_ano'), 'producao_mensal', ['ano'], unique=False)
    op.create_index(op.f('ix_producao_mensal_associacao_id'), 'producao_mensal', ['associacao_id'], unique=False)
    op.create_index(op.f('ix_producao_mensal_id'), 'producao_mensal', ['id'], unique=False)
    op.create_table('transacoes_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tipotransacaoenum'), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('id_compra_associada', sa.Integer(), nullable=True),
    sa.Column('id_venda_associada', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_compra_associada'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['id_venda_associada'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_financeiras_id'), 'transacoes_financeiras', ['id'], unique=False)
    op.create_index(op.f('ix_transacoes_financeiras_tipo'), 'transacoes_financeiras', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacoes_financeiras_tipo'), table_name='transacoes_financeiras')
    op.drop_index(op.f('ix_transacoes_financeiras_id'), table_name='transacoes_financeiras')
    op.drop_table('transacoes_financeiras')
    op.drop_index(op.f('ix_producao_mensal_id'), table_name='producao_mensal')
    op.drop_index(op.f('ix_producao_mensal_associacao_id'), table_name='producao_mensal')
    op.drop_index(op.f('ix_producao_mensal_ano'), table_name='producao_mensal')
    op.drop_table('producao_mensal')
    op.drop_index(op.f('ix_recebimentos_doacao_id'), table_name='recebimentos_doacao')
    op.drop_index(op.f('ix_recebimentos_doacao_codigo_lote'), table_name='recebimentos_doacao')
    op.drop_table('recebimentos_doacao')
    op.drop_index(op.f('ix_itens_venda_id'), table_name='itens_venda')
    op.drop_table('itens_venda')
    op.drop_index(op.f('ix_compras_id'), table_name='compras')
    op.drop_index(op.f('ix_compras_codigo_compra'), table_name='compras')
    op.drop_table('compras')
    op.drop_index(op.f('ix_associacoes_id'), table_name='associacoes')
    op.drop_index(op.f('ix_associacoes_cnpj'), table_name='associacoes')
    op.drop_table('associacoes')
    op.drop_index(op.f('ix_vendas_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_codigo'), table_name='vendas')
    op.drop_table('vendas')
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_parceiros_nome'), table_name='parceiros')
    op.drop_index(op.f('ix_parceiros_id'), table_name='parceiros')
    op.drop_table('parceiros')
    op.drop_index(op.f('ix_materiais_nome'), table_name='materiais')
    op.drop_index(op.f('ix_materiais_id'), table_name='materiais')
    op.drop_index(op.f('ix_materiais_codigo'), table_name='materiais')
    op.drop_table('materiais')
    op.drop_index(op.f('ix_audit_logs_usuario_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_acao'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipo_parceiro_id'), table_name='tipo_parceiro')
    op.drop_table('tipo_parceiro')
    op.drop_index(op.f('ix_enderecos_cache_id'), table_name='enderecos_cache')
    op.drop_index(op.f('ix_enderecos_cache_cnpj'), table_name='enderecos_cache')
    op.drop_table('enderecos_cache')
    op.drop_index(op.f('ix_compradores_nome'), table_name='compradores')
    op.drop_index(op.f('ix_compradores_id'), table_name='compradores')
    op.drop_index(op.f('ix_compradores_cnpj'), table_name='compradores')
    op.drop_table('compradores')
    op.drop_index(op.f('ix_categoria_residuo_nome'), table_name='categoria_residuo')
    op.drop_index(op.f('ix_categoria_residuo_id'), table_name='categoria_residuo')
    op.drop_table('categoria_residuo')
    # ### end Alembic commands ###
