"""Ajusta TransacaoFinanceira para usar ENUM e descricao opcional

Revision ID: f8b17a4befaa
Revises: 66203f355943
Create Date: 2025-11-12 12:30:12.322672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b17a4befaa'
down_revision: Union[str, Sequence[str], None] = '66203f355943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacoes_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tipotransacaoenum'), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('id_compra_associada', sa.Integer(), nullable=True),
    sa.Column('id_venda_associada', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_compra_associada'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['id_venda_associada'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_financeiras_id'), 'transacoes_financeiras', ['id'], unique=False)
    op.create_index(op.f('ix_transacoes_financeiras_tipo'), 'transacoes_financeiras', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacoes_financeiras_tipo'), table_name='transacoes_financeiras')
    op.drop_index(op.f('ix_transacoes_financeiras_id'), table_name='transacoes_financeiras')
    op.drop_table('transacoes_financeiras')
    # ### end Alembic commands ###
